# Site settings
title: "I make games for food"
email: contact@monkeymoon.net
author: "Laurent Victorino"
description: "Advice, pro-tips, and bananas about the business of video game development."
baseurl: ""
url: "http://lvictorino.com"
google_analytics: UA-55229677-1
animated: true

# Build settings
markdown: kramdown
permalink: date
paginate: 10
sass:
  compressed: true

